2020-02-06 16:02:54 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('tecnologia@grup...')
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('tecnologia@grup...')
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/MassEntityAPIHandler.php(326): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Contact_Name:eq...')
#6 /opt/lampp/htdocs/portal/models/api_model.php(27): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Contact_Name:eq...')
#7 /opt/lampp/htdocs/portal/models/deals_model.php(9): api_model->searchRecordsByCriteria('Deals', 'Contact_Name:eq...')
#8 /opt/lampp/htdocs/portal/controllers/portal_controller.php(14): deals_model->resumen()
#9 /opt/lampp/htdocs/portal/index.php(13): portal_controller->pagina_principal()
#10 {main}
2020-02-06 16:04:18 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('tecnologia@grup...')
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('tecnologia@grup...')
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/MassEntityAPIHandler.php(326): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Contact_Name:eq...')
#6 /opt/lampp/htdocs/portal/models/api_model.php(27): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Contact_Name:eq...')
#7 /opt/lampp/htdocs/portal/models/deals_model.php(9): api_model->searchRecordsByCriteria('Deals', 'Contact_Name:eq...')
#8 /opt/lampp/htdocs/portal/controllers/portal_controller.php(14): deals_model->resumen()
#9 /opt/lampp/htdocs/portal/index.php(13): portal_controller->pagina_principal()
#10 {main}
2020-02-06 16:04:31 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('tecnologia@grup...')
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('tecnologia@grup...')
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/MassEntityAPIHandler.php(326): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', 'Contact_Name:eq...')
#6 /opt/lampp/htdocs/portal/models/api_model.php(27): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('Contact_Name:eq...')
#7 /opt/lampp/htdocs/portal/models/deals_model.php(9): api_model->searchRecordsByCriteria('Deals', 'Contact_Name:eq...')
#8 /opt/lampp/htdocs/portal/controllers/portal_controller.php(14): deals_model->resumen()
#9 /opt/lampp/htdocs/portal/index.php(13): portal_controller->pagina_principal()
#10 {main}
2020-02-06 17:09:08 INFO: Access Token has expired. Hence refreshing.
2020-02-06 17:47:08 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(93)
Trace::#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 /opt/lampp/htdocs/portal/models/api_model.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL)
#7 /opt/lampp/htdocs/portal/models/deals_model.php(83): api_model->getRecord('Quotes', NULL)
#8 /opt/lampp/htdocs/portal/controllers/portal_controller.php(60): deals_model->detalles()
#9 /opt/lampp/htdocs/portal/index.php(29): portal_controller->ver_cotizacion()
#10 {main}
2020-02-06 17:47:44 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(93)
Trace::#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 /opt/lampp/htdocs/portal/models/api_model.php(71): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL)
#7 /opt/lampp/htdocs/portal/models/deals_model.php(83): api_model->getRecord('Quotes', NULL)
#8 /opt/lampp/htdocs/portal/controllers/portal_controller.php(60): deals_model->detalles()
#9 /opt/lampp/htdocs/portal/index.php(29): portal_controller->ver_cotizacion()
#10 {main}
2020-02-06 22:03:58 INFO: Access Token has expired. Hence refreshing.
2020-02-06 22:04:10 INFO: Access Token has expired. Hence refreshing.
2020-02-06 22:05:21 INFO: Access Token has expired. Hence refreshing.
2020-02-06 23:56:01 INFO: Access Token has expired. Hence refreshing.
2020-02-07 00:00:23 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'No Content' in /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/BulkAPIResponse.php(61)
Trace::#0 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#3 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/api/handler/MassEntityAPIHandler.php(326): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /opt/lampp/htdocs/portal/api/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1131): zcrmsdk\crm\api\handler\MassEntityAPIHandler->searchRecords(Array, 'criteria', '((Usuario:equal...')
#6 /opt/lampp/htdocs/portal/models/api_model.php(27): zcrmsdk\crm\crud\ZCRMModule->searchRecordsByCriteria('((Usuario:equal...')
#7 /opt/lampp/htdocs/portal/controllers/login_controller.php(11): api_model->searchRecordsByCriteria('Contacts', '((Usuario:equal...')
#8 /opt/lampp/htdocs/portal/index.php(54): login_controller->autenticacion()
#9 {main}
